version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5298:5298"
    depends_on:
      - mongodb

volumes:
  mongodb_data: